### PR TITLE
AX not sent on some rejections

### LINKED ISSUE #297: AX not sent on bad requests
```
2021-07-29T15:48:47.436Z	DEBUG	server/authorization.go:122	environment spec: spec-1
2021-07-29T15:48:47.436Z	DEBUG	server/authorization.go:130	api: petstore
2021-07-29T15:48:47.436Z	DEBUG	server/authorization.go:142	operation: headers
2021-07-29T15:48:47.436Z	DEBUG	config/env_spec_request.go:304	using AuthenticationRequirement from operation "headers"
2021-07-29T15:48:47.436Z	DEBUG	config/env_spec_request.go:162	param from header "authorization": "Beare..."
2021-07-29T15:48:47.600Z	DEBUG	config/env_spec_request.go:234	JWTAuthentication "test_oidc" verification error: jwt.Parse: failed to find matching key for verification: failed to parse token data: invalid byte sequence
2021-07-29T15:48:47.601Z	DEBUG	server/authorization.go:145	authentication requirements not met
2021-07-29T15:48:47.601Z	DEBUG	server/authorization.go:504	sending downstream: UNAUTHENTICATED
2021-07-29T15:48:47.852Z	DEBUG	server/accesslog.go:104	props: &envoy_data_accesslog_v3.AccessLogCommon{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), SampleRate:0, DownstreamRemoteAddress:(*envoy_config_core_v3.Address)(0xc0003036c0), DownstreamLocalAddress:(*envoy_config_core_v3.Address)(0xc000303740), TlsProperties:(*envoy_data_accesslog_v3.TLSProperties)(nil), StartTime:(*timestamppb.Timestamp)(0xc000303780), TimeToLastRxByte:(*durationpb.Duration)(0xc0003038c0), TimeToFirstUpstreamTxByte:(*durationpb.Duration)(nil), TimeToLastUpstreamTxByte:(*durationpb.Duration)(nil), TimeToFirstUpstreamRxByte:(*durationpb.Duration)(nil), TimeToLastUpstreamRxByte:(*durationpb.Duration)(nil), TimeToFirstDownstreamTxByte:(*durationpb.Duration)(0xc000303980), TimeToLastDownstreamTxByte:(*durationpb.Duration)(0xc000303c00), UpstreamRemoteAddress:(*envoy_config_core_v3.Address)(nil), UpstreamLocalAddress:(*envoy_config_core_v3.Address)(nil), UpstreamCluster:"", ResponseFlags:(*envoy_data_accesslog_v3.ResponseFlags)(nil), Metadata:(*envoy_config_core_v3.Metadata)(nil), UpstreamTransportFailureReason:"", RouteName:"", DownstreamDirectRemoteAddress:(*envoy_config_core_v3.Address)(0xc000303d00), FilterStateObjects:map[string]*anypb.Any(nil)}
2021-07-29T15:48:47.852Z	DEBUG	server/accesslog.go:122	No dynamic metadata for ext_authz filter, falling back to headers
2021-07-29T15:48:47.852Z	DEBUG	server/header_context.go:50	No context header x-apigee-api or api header: :authority
2021-07-29T15:48:47.852Z	DEBUG	server/accesslog.go:130	Unknown target, skipped accesslog: &envoy_data_accesslog_v3.HTTPRequestProperties{state:impl.MessageState{NoUnkeyedLiterals:pragma.NoUnkeyedLiterals{}, DoNotCompare:pragma.DoNotCompare{}, DoNotCopy:pragma.DoNotCopy{}, atomicMessageInfo:(*impl.MessageInfo)(nil)}, sizeCache:0, unknownFields:[]uint8(nil), RequestMethod:1, Scheme:"http", Authority:"httpbin.org", Port:(*wrapperspb.UInt32Value)(nil), Path:"/v1/headers", UserAgent:"curl/7.74.0", Referer:"", ForwardedFor:"", RequestId:"2c095fd7-913e-46d9-bec7-b3812a04829b", OriginalPath:"", RequestHeadersBytes:0xb0, RequestBodyBytes:0x0, RequestHeaders:map[string]string(nil)}
```

The request path was sufficient for us to find the api and operation. But because it was a 401, no `x-apigee-api` was appended and accesslog got skipped. I think we need to log this type of requests.

### PR DESCRIPTION
**Pull request by theganyo**
Closes #297

### CODE REVIEW

File: server/authorization.go [hunk 1]
```diff
@@ -523,7 +523,12 @@ func (a *AuthorizationServer) createEnvoyDenied(req *authv3.CheckRequest, envReq
 
 	// Envoy does not send metadata to ALS on a reject, so we create the
 	// analytics record here and the ALS handler can ignore the metadataless record.
-	if authContext != nil && api != "" {
+	if tracker != nil { // if no tracker, we don't even have org and env context
+		if authContext == nil {
```
Comment (rockspore) [inline server/authorization.go:527]: Can we have a debug log in this block. It's currently not visible so rather difficult to tell.

Comment (theganyo) [reply server/authorization.go:527]: This can only happen when called here, so it's already logged once: https://github.com/apigee/apigee-remote-service-envoy/blob/2f9789b0f70d82c2e0f2d93bd8c15506c624106c/server/authorization.go#L126

Comment (theganyo) [reply server/authorization.go:527]: Oops. Sorry, wrong line. https://github.com/apigee/apigee-remote-service-envoy/blob/2f9789b0f70d82c2e0f2d93bd8c15506c624106c/server/authorization.go#L71

**Review by rockspore — APPROVED** [review]

File: server/authorization.go (hunk 1 above)
Comment (theganyo) [reply server/authorization.go:527]: I'll add it
