### PR TITLE
If there are no operations for an api, assume a "match all" operation

### LINKED ISSUE #271: If there are no operations for an api, assume a "match all" operation
Currently, an api without operations will always fail as there is no match. Instead, it should succeed as if an operation exists that allows all methods and paths.

### PR DESCRIPTION
**Pull request by theganyo**
Fixes #271

### CODE REVIEW

File: config/env_spec_request.go [hunk 1]
```diff
@@ -30,6 +30,11 @@ import (
 
 const TruncateDebugRequestValuesAt = 5
 
+// a "match all" operation for apis without operations
+var synthesizedOperation = &APIOperation{
+	Name: "*",
```
Comment (rockspore) [inline config/env_spec_request.go:35]: Just wanted to confirm, do we indeed disallow such a name?

Comment (rockspore) [reply config/env_spec_request.go:35]: nvm, I realize it doesn't matter.

**Review by rockspore — APPROVED** [review]

File: config/env_spec_request.go (hunk 1 above)
Comment (theganyo) [reply config/env_spec_request.go:35]: We don't validate against it, but since it's only used when there are no operations, it can't conflict with anything.
